[tool.poetry]
name = "qksolver"
version = "0.1.0"
description = ""
authors = ["Kyosuke Miyamura <ask@386.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
